title: Monerujo
description: Monerujo, an android lightwallet for Monero
baseurl: ""
permalink: date
exclude: [".gitignore", "README.md", "Gemfile", "Gemfile.lock"]
# Plugins
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate

# paginate
paginate: 10
paginate_path: "blog/page:num/"

# jekyll-multiple-languages-plugin settings:
languages: ["en", "es", "fr"]

exclude_from_localizations: ["img", "css", "font", "_posts"]
